services:
  jaeger:
    image: repo.mhe.io/docker/jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
    expose:
      - 14268
      - 4317
      - 4318
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "4318:4318"
volumes: {}
