openapi: 3.1.0
info:
  description: 'Connect Playground API Documentation'
  title: Example Platform
  version: v1.0.0
paths:
  /azuka.connect.playground.api.v1.TodoService/Create:
    post:
      tags:
        - azuka.connect.playground.api.v1.TodoService
      summary: Create
      description: Create todo
      operationId: azuka.connect.playground.api.v1.TodoService.Create
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/azuka.connect.playground.api.v1.TodoServiceCreateRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/azuka.connect.playground.api.v1.TodoServiceCreateResponse'
  /azuka.connect.playground.api.v1.TodoService/Update:
    post:
      tags:
        - azuka.connect.playground.api.v1.TodoService
      summary: Update
      description: Update todo
      operationId: azuka.connect.playground.api.v1.TodoService.Update
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/azuka.connect.playground.api.v1.TodoServiceUpdateRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/azuka.connect.playground.api.v1.TodoServiceUpdateResponse'
  /azuka.connect.playground.api.v1.TodoService/Get:
    post:
      tags:
        - azuka.connect.playground.api.v1.TodoService
      summary: Get
      description: Get todo
      operationId: azuka.connect.playground.api.v1.TodoService.Get
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/azuka.connect.playground.api.v1.TodoServiceGetRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/azuka.connect.playground.api.v1.TodoServiceGetResponse'
  /azuka.connect.playground.api.v1.TodoService/List:
    post:
      tags:
        - azuka.connect.playground.api.v1.TodoService
      summary: List
      description: List todos with filters
      operationId: azuka.connect.playground.api.v1.TodoService.List
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/azuka.connect.playground.api.v1.TodoServiceListRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/azuka.connect.playground.api.v1.TodoServiceListResponse'
  /azuka.connect.playground.api.v1.TodoService/Delete:
    post:
      tags:
        - azuka.connect.playground.api.v1.TodoService
      summary: Delete
      description: Delete todo
      operationId: azuka.connect.playground.api.v1.TodoService.Delete
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/azuka.connect.playground.api.v1.TodoServiceDeleteRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/azuka.connect.playground.api.v1.TodoServiceDeleteResponse'
components:
  schemas:
    azuka.connect.playground.api.v1.Pagination:
      type: object
      properties:
        total:
          oneOf:
            - type: string
            - type: number
          title: total
        nextToken:
          type: string
          title: next_token
        previousToken:
          type: string
          title: previous_token
        page:
          oneOf:
            - type: string
            - type: number
          title: page
        limit:
          oneOf:
            - type: string
            - type: number
          title: limit
      title: Pagination
      additionalProperties: false
    connect-protocol-version:
      type: number
      title: Connect-Protocol-Version
      enum:
        - 1
      description: Define the version of the Connect protocol
      const: 1
    connect-timeout-header:
      type: number
      title: Connect-Timeout-Ms
      description: Define the timeout, in ms
    connect.error:
      type: object
      properties:
        code:
          type: string
          examples:
            - CodeNotFound
          enum:
            - CodeCanceled
            - CodeUnknown
            - CodeInvalidArgument
            - CodeDeadlineExceeded
            - CodeNotFound
            - CodeAlreadyExists
            - CodePermissionDenied
            - CodeResourceExhausted
            - CodeFailedPrecondition
            - CodeAborted
            - CodeOutOfRange
            - CodeInternal
            - CodeUnavailable
            - CodeDataLoss
            - CodeUnauthenticated
          description: The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
        message:
          type: string
          description: A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
        detail:
          $ref: '#/components/schemas/google.protobuf.Any'
      title: Connect Error
      additionalProperties: true
      description: 'Error type returned by Connect: https://connectrpc.com/docs/go/errors/#http-representation'
    google.protobuf.Any:
      type: object
      properties:
        type:
          type: string
        value:
          type: string
          format: binary
        debug:
          type: object
          additionalProperties: true
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
    azuka.connect.playground.api.v1.TodoServiceCreateRequest:
      type: object
      properties:
        name:
          type: string
          title: name
        when:
          $ref: '#/components/schemas/google.protobuf.Timestamp'
      title: TodoServiceCreateRequest
      additionalProperties: false
    azuka.connect.playground.api.v1.TodoServiceCreateResponse:
      type: object
      properties:
        uuid:
          type: string
          title: uuid
        name:
          type: string
          title: name
        when:
          $ref: '#/components/schemas/google.protobuf.Timestamp'
        createdAt:
          $ref: '#/components/schemas/google.protobuf.Timestamp'
        updatedAt:
          $ref: '#/components/schemas/google.protobuf.Timestamp'
      title: TodoServiceCreateResponse
      additionalProperties: false
    azuka.connect.playground.api.v1.TodoServiceDeleteRequest:
      type: object
      properties:
        uuid:
          type: string
          title: uuid
      title: TodoServiceDeleteRequest
      additionalProperties: false
    azuka.connect.playground.api.v1.TodoServiceDeleteResponse:
      type: object
      title: TodoServiceDeleteResponse
      additionalProperties: false
    azuka.connect.playground.api.v1.TodoServiceGetRequest:
      type: object
      properties:
        uuid:
          type: string
          title: uuid
      title: TodoServiceGetRequest
      additionalProperties: false
    azuka.connect.playground.api.v1.TodoServiceGetResponse:
      type: object
      properties:
        uuid:
          type: string
          title: uuid
        name:
          type: string
          title: name
        when:
          $ref: '#/components/schemas/google.protobuf.Timestamp'
        createdAt:
          $ref: '#/components/schemas/google.protobuf.Timestamp'
        updatedAt:
          $ref: '#/components/schemas/google.protobuf.Timestamp'
      title: TodoServiceGetResponse
      additionalProperties: false
    azuka.connect.playground.api.v1.TodoServiceListRequest:
      type: object
      properties:
        filter:
          type: string
          title: filter
        pageIndex:
          type: integer
          title: page_index
        pageSize:
          type: integer
          title: page_size
          maximum: 200
      title: TodoServiceListRequest
      additionalProperties: false
    azuka.connect.playground.api.v1.TodoServiceListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/azuka.connect.playground.api.v1.TodoServiceCreateResponse'
          title: items
        pagination:
          $ref: '#/components/schemas/azuka.connect.playground.api.v1.Pagination'
      title: TodoServiceListResponse
      additionalProperties: false
    azuka.connect.playground.api.v1.TodoServiceUpdateRequest:
      type: object
      properties:
        uuid:
          type: string
          title: uuid
        when:
          $ref: '#/components/schemas/google.protobuf.Timestamp'
      title: TodoServiceUpdateRequest
      additionalProperties: false
    azuka.connect.playground.api.v1.TodoServiceUpdateResponse:
      type: object
      properties:
        uuid:
          type: string
          title: uuid
        name:
          type: string
          title: name
        when:
          $ref: '#/components/schemas/google.protobuf.Timestamp'
        createdAt:
          $ref: '#/components/schemas/google.protobuf.Timestamp'
        updatedAt:
          $ref: '#/components/schemas/google.protobuf.Timestamp'
      title: TodoServiceUpdateResponse
      additionalProperties: false
    google.protobuf.Timestamp:
      type: string
      format: date-time
      description: |-
        A Timestamp represents a point in time independent of any time zone or local
         calendar, encoded as a count of seconds and fractions of seconds at
         nanosecond resolution. The count is relative to an epoch at UTC midnight on
         January 1, 1970, in the proleptic Gregorian calendar which extends the
         Gregorian calendar backwards to year one.

         All minutes are 60 seconds long. Leap seconds are "smeared" so that no leap
         second table is needed for interpretation, using a [24-hour linear
         smear](https://developers.google.com/time/smear).

         The range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z. By
         restricting to that range, we ensure that we can convert to and from [RFC
         3339](https://www.ietf.org/rfc/rfc3339.txt) date strings.

         # Examples

         Example 1: Compute Timestamp from POSIX `time()`.

             Timestamp timestamp;
             timestamp.set_seconds(time(NULL));
             timestamp.set_nanos(0);

         Example 2: Compute Timestamp from POSIX `gettimeofday()`.

             struct timeval tv;
             gettimeofday(&tv, NULL);

             Timestamp timestamp;
             timestamp.set_seconds(tv.tv_sec);
             timestamp.set_nanos(tv.tv_usec * 1000);

         Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.

             FILETIME ft;
             GetSystemTimeAsFileTime(&ft);
             UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;

             // A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z
             // is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.
             Timestamp timestamp;
             timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));
             timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));

         Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.

             long millis = System.currentTimeMillis();

             Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)
                 .setNanos((int) ((millis % 1000) * 1000000)).build();

         Example 5: Compute Timestamp from Java `Instant.now()`.

             Instant now = Instant.now();

             Timestamp timestamp =
                 Timestamp.newBuilder().setSeconds(now.getEpochSecond())
                     .setNanos(now.getNano()).build();

         Example 6: Compute Timestamp from current time in Python.

             timestamp = Timestamp()
             timestamp.GetCurrentTime()

         # JSON Mapping

         In JSON format, the Timestamp type is encoded as a string in the
         [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format. That is, the
         format is "{year}-{month}-{day}T{hour}:{min}:{sec}[.{frac_sec}]Z"
         where {year} is always expressed using four digits while {month}, {day},
         {hour}, {min}, and {sec} are zero-padded to two digits each. The fractional
         seconds, which can go up to 9 digits (i.e. up to 1 nanosecond resolution),
         are optional. The "Z" suffix indicates the timezone ("UTC"); the timezone
         is required. A proto3 JSON serializer should always use UTC (as indicated by
         "Z") when printing the Timestamp type and a proto3 JSON parser should be
         able to accept both UTC and other timezones (as indicated by an offset).

         For example, "2017-01-15T01:30:15.01Z" encodes 15.01 seconds past
         01:30 UTC on January 15, 2017.

         In JavaScript, one can convert a Date object to this format using the
         standard
         [toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
         method. In Python, a standard `datetime.datetime` object can be converted
         to this format using
         [`strftime`](https://docs.python.org/2/library/time.html#time.strftime) with
         the time format spec '%Y-%m-%dT%H:%M:%S.%fZ'. Likewise, in Java, one can use
         the Joda Time's [`ISODateTimeFormat.dateTime()`](
         http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime()
         ) to obtain a formatter capable of generating timestamps in this format.
security: []
tags:
  - name: azuka.connect.playground.api.v1.TodoService
